# Generated by Django 5.2.1 on 2025-06-06 21:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('shipping_address', models.TextField(default='Address to be provided')),
                ('shipping_city', models.CharField(default='City to be provided', max_length=100)),
                ('shipping_postal_code', models.CharField(default='00000', max_length=20)),
                ('shipping_country', models.CharField(default='Country to be provided', max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(default='credit_card', max_length=50)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'), models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'), models.Index(fields=['tracking_number'], name='orders_orde_trackin_04edf9_idx')],
            },
        ),
    ]
