# Generated by Django 5.2.1 on 2025-07-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemimage_promotion'),
        ('orders', '0003_remove_order_orders_orde_status_25e057_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_5d347b_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_item_id_1cec6c_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='promos',
            field=models.ManyToManyField(blank=True, related_name='promos', to='items.promotion'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
    ]
