# Generated by Django 5.2.4 on 2025-07-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_item_image_remove_item_item_images'),
        ('orders', '0004_remove_orderitem_orders_orde_order_i_5d347b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='items.item'),
        ),
    ]
