# Generated by Django 6.0 on 2026-03-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitemcancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_pending',
            field=models.BooleanField(default=False, help_text='True when a refund should be issued for cancelled items'),
        ),
    ]
