# Generated by Django 5.2.1 on 2025-07-02 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_description',
            new_name='item_desc',
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this review is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='response_date',
            field=models.DateTimeField(blank=True, help_text='When seller responded', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_response',
            field=models.TextField(blank=True, help_text="Seller's response to this review"),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('electronics', 'Electronics & Tech'), ('clothing', 'Clothing & Fashion'), ('home_kitchen', 'Home & Kitchen'), ('books_media', 'Books & Media'), ('sports_outdoors', 'Sports & Outdoors'), ('beauty_personal', 'Beauty & Personal Care'), ('toys_games', 'Toys & Games'), ('automotive', 'Automotive & Tools'), ('health_wellness', 'Health & Wellness'), ('jewelry_accessories', 'Jewelry & Accessories'), ('baby_kids', 'Baby & Kids'), ('pet_supplies', 'Pet Supplies'), ('office_supplies', 'Office & School Supplies'), ('collectibles', 'Collectibles & Art'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['item', '-helpful_count'], name='items_revie_item_id_337a63_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order'], name='items_revie_order_i_ebe37e_idx'),
        ),
    ]
