# Generated by Django 5.2.1 on 2025-07-05 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order this review is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_category', 'is_available'], name='items_item_item_ca_63b67e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['custom_category', 'is_available'], name='items_item_custom__72e548_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['seller', 'is_available'], name='items_item_seller__af27db_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_featured', 'is_available'], name='items_item_is_feat_24292e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_on_sale', 'is_available'], name='items_item_is_on_s_35deb6_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_price'], name='items_item_item_pr_7564fe_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['view_count'], name='items_item_view_co_b9e501_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['times_purchased'], name='items_item_times_p_11abbf_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['item', 'rating'], name='items_revie_item_id_c94854_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='items_revie_reviewe_d4e301_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['item', '-helpful_count'], name='items_revie_item_id_337a63_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order'], name='items_revie_order_i_ebe37e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('item', 'reviewer')},
        ),
    ]
