# Generated by Django 5.2.1 on 2025-07-10 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
        ('orders', '0003_remove_order_orders_orde_status_25e057_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_view_co_b9e501_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_times_p_11abbf_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='media',
            field=models.FileField(blank=True, help_text='Optional image or video attachment (max 100MB)', null=True, upload_to='reviews/media/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, help_text='Review from verified buyer (automatically set)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_available', '-view_count'], name='items_item_is_avai_50bf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_available', '-times_purchased'], name='items_item_is_avai_71288d_idx'),
        ),
    ]
