# Generated by Django 5.2.1 on 2025-07-19 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_review_unique_together_review_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='item_images/default.png', upload_to='item_images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('item', 'Item Specific'), ('checkout', 'Total Cost'), ('seller', 'Seller Specific')], max_length=10)),
                ('code', models.CharField(help_text='Promo code/ Coupon has to be less than 10 in length', max_length=10)),
                ('discount_method', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], max_length=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, help_text='Optional description for this promotion')),
                ('items', models.ManyToManyField(blank=True, related_name='promo', to='items.item')),
                ('sellers', models.ManyToManyField(blank=True, related_name='promo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at'],
                'indexes': [models.Index(fields=['promo_type'], name='items_promo_promo_t_a31e27_idx')],
            },
        ),
    ]
