# Generated by Django 5.2.1 on 2025-07-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemimage_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_images',
        ),
    ]
