# Generated by Django 5.2.4 on 2025-07-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_item_image_remove_item_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default='../media/item_images/default.png', upload_to='../media/item_images/'),
        ),
    ]
