# Generated by Django 5.2.4 on 2025-07-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_itemimage_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='image',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image_file',
            field=models.ImageField(default='item_images/default.png', upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image_url',
            field=models.CharField(blank=True),
        ),
    ]
