# Generated by Django 4.2 on 2025-12-22 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0008_alter_itemimage_item'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_is_feat_24292e_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_dimensions',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='technical_specs',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='image',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='helpful_count',
            field=models.IntegerField(default=0),
        ),
    ]
