# Generated by Django 5.2.4 on 2025-08-02 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_itemimage_image_itemimage_image_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('open_box', 'Open Box'), ('refurbished', 'Refurbished')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='helpful_count',
            field=models.IntegerField(default=0),
        ),
    ]
