# Generated by Django 6.0 on 2025-12-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_item_items_item_is_feat_24292e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
