# Generated by Django 5.2.4 on 2025-08-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_review_upvoted_by_alter_item_item_condition_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='items_item_is_feat_24292e_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_dimensions',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='technical_specs',
        ),
    ]
