# Generated by Django 5.2.4 on 2025-08-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_item_items_item_is_feat_24292e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
