# Generated by Django 5.2.1 on 2025-07-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_users_profi_is_sell_41b00c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_notifications',
        ),
    ]
