# Generated by Django 4.2 on 2025-12-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_ava/default.png', upload_to='profile_ava'),
        ),
    ]
